services:
    smsapi_client:
        class: SMSApi\Client
        arguments: 
            - 'sms@aveqimedia.nl'        
        calls:
            - method: setPasswordHash
              arguments: ['%brandcode_nl_sonata_smsapi_publisher.api_key%']
        public: false
        
    smsapi_api:
        class: SMSApi\Api\SmsFactory
        arguments:
            - 'sms@aveqimedia.nl'
        calls:
            - method: setClient
              arguments:
                - '@smsapi_client'
        public: false
    
    brandcode_nl_sonata_smsapi.phone_number_provider:
        class: BrandcodeNL\SonataSmsapiPublisherBundle\Provider\PhoneNumberProvider

    brandcode_nl_sonata_smsapi.content_provider:
        class: BrandcodeNL\SonataSmsapiPublisherBundle\Provider\ContentProvider

    brandcode_nl_sonata_smsapi_publisher.channel:
        class: BrandcodeNL\SonataSmsapiPublisherBundle\Channel\SMSChannel            
        arguments: 
            - '@smsapi_api'
            - '@brandcode_nl_sonata_smsapi.phone_number_provider'
            - '@brandcode_nl_sonata_smsapi.content_provider'
        tags:
            - { name: sonata_publisher.channel } 
        public: false